/**
 * Renders one or more JSON-LD blocks. Accepts nulls so callers can pass
 * `faqSchema(faqs)` directly without guarding for empty FAQ lists.
 */
export default function JsonLd({
  data,
}: {
  data: (object | null)[] | object | null;
}) {
  const blocks = (Array.isArray(data) ? data : [data]).filter(Boolean) as object[];
  return (
    <>
      {blocks.map((block, i) => (
        <script
          key={i}
          type="application/ld+json"
          // Content is generated by our own schema builders, never user input.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(block) }}
        />
      ))}
    </>
  );
}
